version: '3'
services:
  cloudorchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudorchestrator
    depends_on:
    - mariadb
    - memcached
    restart: unless-stopped
    ports:
    - 80:80
    environment:
      DrupalUserName: cloud_admin
      DrupalPassword: cloud_admin
      DrupalEmail: onotm@intellilink.co.jp
      DatabaseName: &DatabaseName cloud_orchestrator
      MySQLUserName: &MySQLUserName administrator
      MySQLPassword: &MySQLPassword administrator

  mariadb:
    image: mariadb:10.6-focal
    container_name: mariadb
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: *MySQLPassword
      MYSQL_USER: *MySQLUserName
      MYSQL_PASSWORD: *MySQLPassword
      MYSQL_DATABASE: *DatabaseName

  memcached:
    image: memcached:1.6
    container_name: memcached
    restart: unless-stopped
    ports:
    - 11211:11211
